apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: flask-app
type: Opaque
data:
  db_name: YXBwZGI=  # base64 for "appdb"
  db_user: YXBwdXNlcg==  # base64 for "appuser"
  db_password: c2VjdXJlcGFzc3dvcmQxMjM=  # base64 for "securepassword123"
  db_host: <base64_rds_endpoint>  # Replace with base64 of RDS endpoint