name: CI/CD Pipeline
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build Docker image
      run: docker build -t ghcr.io/gauravkumar1430/flask-app:${{ github.sha }} ./app
    - name: Push to GHCR
      run: |
        echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/yourusername/flask-app:${{ github.sha }}
    - name: Deploy to EKS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1
    - name: Update Kubernetes
      run: |
        kubectl set image deployment/flask-app flask-app=ghcr.io/yourusername/flask-app:${{ github.sha }} -n default