---
- hosts: on_prem
  become: yes
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes
    - name: Install Git
      apt:
        name: git
        state: present
    - name: Clone repository
      git:
        repo: 'https://github.com/gauravkumar1430/app-repo.git'
        dest: /app
        version: main